print("What's your name?")
myName = input()
print("Hello " + myName + ". That is a good name. How old are you?")
myAge = input()
print(myAge + "? That's funny, I'm only a few seconds old.")
print("I wish I was " + str(int(myAge) * 2) + " years old") 